version = 0.1
[test]
[test.deploy]
[test.deploy.parameters]
stack_name = "gamified-backend-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5yhxs1anz0ik"
s3_prefix = "gamified-backend-test"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gamified-backend-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5yhxs1anz0ik"
s3_prefix = "gamified-backend-test"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
